version: '3.8'

services:
  user-db:
    image: postgres:13
    container_name: user-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  product-db:
    image: postgres:13
    container_name: product-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  order-db:
    image: postgres:13
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

volumes:
  user_data:
  product_data:
  order_data:
